### ISSUE TITLE
Behaviour of forward-unbound-keys

### ISSUE THREAD

**Issue by lahwaacz** [The-Compiler/qutebrowser#1258]
If `forward-unbound-keys` is `auto` (default), only non-alphanumeric keys are forwarded - including space, special symbols like `!@#$%^&*` and arrows, but not e.g. `,.[]()`. Is it some strange definition of alphanumeric keys or a bug?

If `forward-unbound-keys` is `none`, then none keys are actually forwarded, including `Ctrl+c`, which is currently the only key I want to forward. Is there a way to do this?

Btw, is it possible to disable cursor blinking when the insert mode is not active?

**Comment by The-Compiler** [comment]
None of `!@#$%^&*` is forwarded for me. Are you running anything pre-v0.5.0 by any chance? There was a bug there which allowed any character to be passed through with shift (which would match the characters you mentioned), and it was fixed in c1d3a94936c9c44457d6f43b54ec717ff5a7b2ef.

> Btw, is it possible to disable cursor blinking when the insert mode is not active?

Unfortunately I haven't found a good way to do this.

**Comment by lahwaacz** [comment]
I'm at faed088735748beeb922bff3362ae7d4bc7b4d12.

On my keyboard layout (`cz`) the special characters that were forwarded are `AltGr+<num>`, but e.g. the square brackets (`AltGr+f`/`AltGr+g`) were not forwarded.

**Comment by The-Compiler** [comment]
I just merged a complete refactoring on how keys are handled to `master` - @lahwaacz, can you please re-try with that?

**Comment by lahwaacz** [comment]
I'll try it in the weekend.

**Comment by lahwaacz** [comment]
Well, the square brackets are bound by default and if I unbind them, they are forwarded as expected, even with `AltGr+f`/`AltGr+g` on the `cz` keyboard. Other characters which didn't work before (`,.()`) are still not forwarded.

Also note that the forwarding of `@` when it is bound to `:run-macro` is funny: the first time I press `@` nothing happens and the subsequent presses of `@` are forwarded. If I press anything else after `@`, a warning like "No macro recorded in 'k'!" pops up.

**Comment by Aster89** [comment]
@The-Compiler , I see this issue is opened, so is it not solved yet?

**Comment by The-Compiler** [comment]
Correct.
