### ISSUE TITLE
Higher memory usage since 0.9 update.

### ISSUE THREAD

**Issue by throwaway217** [The-Compiler/qutebrowser#2201]
First of all I know measurement of used RAM is not accurate and there's this general feel that RAM should be used as long as it's free but since the latest update qutebrowser has been using twice or three times as much memory resulted from the same browsing patterns. 
Probably since I have a really restrictive config with the 0.8 branch I would get at most somewhere arround 400 both share and private no matter how many tabs or how much usage.
Now I can easely get something like (output taken from ps_mem) without much usage:
786.9 MiB + 101.9 MiB = 888.8 MiB       qutebrowser

Using qutebrowser from the archlinux repos.  Can anyone replicate this ? Here is my config file: http://ix.io/1OEU (you might need to check the proxy setting) and here is qutebrowser --version http://ix.io/1OEV

Would this be a good starting point for me in order to help ?  https://github.com/The-Compiler/qutebrowser/issues/1476#issuecomment-217661122

**Comment by stroobandt** [comment]
I am not seeing this with version 0.9.0 on Xubuntu LTS 16.04 64bit.
The command `free -m` reports a difference in used system memory between not running `qutebrowser` and running it with a single tab open on this page of only 506 - 402 = 158 MB.

**Comment by The-Compiler** [comment]
Yes, a pympler output would certainly be interesting. Are you using the QtWebKit or QtWebEngine backend? Did you also update Qt by any chance?

**Comment by throwaway217** [comment]
Ok, so first I don't want to waste your time.
>proceeds to write incoherent rubbish

Let me put in a few phrases my train of thought and how I came to the conclusion that qutebrowser is using more memory after I updated to 0.9.
I have a minimal system, and it has been like that for more than a year. I'm using bspwm and at all times I have 4 st instances {toxic,newsbeuter,htop,alsamixer} running at all times, on workspace 3 I have a st instance with n
eovim where I do my work and on the second workspace I have qutebrowser running at all times.Background stuff includes tor as you probably realized by looking at the config and sct (flak) which I run at night.After having this
 setup for so much time and always seeing the ram usage in htop around 500 and right after I update to qutebrowser 0.9 RAM usage goes to 860-1200 easely you can see why I'm thinking it's qutebrowser.

The sad part is that I didn't keep tabs on qutebrowser memory usage before updating.Now if I try to downgrade to the latest release of the 0.8 branch I also get increased memory usage but not as much as the 0.9 branch. After s
ome decent usage with that config I would no longer get around 500 Mem {htop} like I used to get before upgrading to 0.9, now with the 0.8 branch I get around max 900 memory usage in htop.

Now either I'm losing my mind or something that qutebrowser depends on was updated along with 0.9 and is causing this.I looked at this and the closest to the qutebrowser archlinux package update date are qt5-base and qt5-webki
t.But the updates are nearly 2 weeks apart. This can be explained easely since I was using an outdated mirror. (I hate to change mirros since the qutebrowser update did not show up after pacman -Syu).

After your suggestion regarding qt and writing all this I think it's not that bad of an idea to downgrade qt5-base and qt5-webkit except now both 0.8.4 and 0.9 won't start with qt5-base 4.7.0 and qt5-webkit 4.7.0

So, after downgrading qt5-base , qt5-webkit to 4.7.0 and qutebrowser to 0.8.4 and updating the packages with pacman -Syu everything works fine, qutebrowser won't even go above 420 RAM no matter what I do.

What should I do now ?

**Comment by throwaway217** [comment]
Here is the pimpler output for:

Private   +   Shared  =  RAM used       Program
871.3 MiB +  86.9 MiB = 958.2 MiB       qutebrowser

                                        types |   # objects |   total size
============================================= | =========== | ============
                                 <class 'dict |       19578 |      6.75 MB
                                  <class 'str |       44445 |      4.82 MB
                                 <class 'type |        1217 |      1.21 MB
                                 <class 'code |        8756 |      1.20 MB
                                 <class 'list |       11427 |      1.11 MB
         <class 'PyQt5.QtCore.pyqtWrapperType |         875 |    882.60 KB
                                <class 'tuple |       11232 |    698.05 KB
  <class 'qutebrowser.browser.hints.HintLabel |        4882 |    686.53 KB
                         <class 'sip.enumtype |         633 |    628.05 KB
                                  <class 'set |        1298 |    626.19 KB
                 <class 'sip.methoddescriptor |       10987 |    600.85 KB
           <class 'PyQt5.QtWebKit.QWebElement |        4882 |    533.97 KB
              <class 'collections.OrderedDict |         868 |    506.20 KB
                    <class 'functools.partial |        5005 |    391.02 KB
                   <class 'wrapper_descriptor |        4662 |    364.22 KB

If I do :open qute:log and /Qt widgets, the search returns nothing.This will work only with certain settings right ?

**Comment by The-Compiler** [comment]
You'll need to run `:debug-all-widgets` for qutebrowser to log that first.

As you can see from tat output, only about ~25MB of RAM is because of Python objects - so either qutebrowser causes C++ to allocate more memory somehow, or it's simply something inside Qt happening.

Still, as there's #1476 already open and I don't know of a good way to track these things down, I'm closing this one for now, until someone has some insight about what could be going on. Sorry I can't say more!

**Comment by throwaway217** [comment]
The reason why I was seeing the same behavior in 0.8.4 is because I downloaded the package from the archlinux package archive that was rebuilt with python 3.6 {0.8.4-2} which and was pushed to the repos on 27 December when I was using outdated mirrors and I upgraded directly from 0.8.4-1.

I realized this a few hours ago and I've been using 0.8.4-1 since then with no problems.

https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/qutebrowser

The python 3.6 rebuild is the culprit.

**Comment by throwaway217** [comment]
qutebrowser is the only sane browsing option I have at my disposal. What should I do in order to get to the bottom of this ?

**Comment by The-Compiler** [comment]
So someone else just reported this in the `#archlinux` IRC channel. Reopening as this seems something different to the usual "there's a memory leak somewhere" thing.

Still, I have no idea how to get to the bottom of this I'm afraid. Since I currently am busy with university exams, this will probably be quiet for at least a month.

**Comment by The-Compiler** [comment]
Something that'd help a lot if you can consistently tell whether there's more memory used or not: Use `git bisect` between v0.9.0 and v0.8.4 to try and find out if there's a responsible qutebrowser commit. Something like this in the repo:

```
$ git bisect start
$ git bisect good v0.8.4
$ git bisect bad v0.9.0
$ python3 -m qutebrowser --temp-basedir
$ git bisect bad/good
```

**Comment by throwaway217** [comment]
Freenode doesn't really like tor and I haven't gotten around to registering a nick and setting up an irc client in a way that satisfies me. I'm going to document myself on bisect and follow your instructions.

**Comment by throwaway217** [comment]
[614794a62a77552483a0b0471f06c9d04e547a75] link_pyqt: Use PyQt5.QtCore to find PyQt5 path

I am unable to test this using git bisect. qutebrowser crashes too often even when I try evading things that make it crash. For example right now this commit makes ESC and o crash the browser. Should I just mark these commits as bad ? I can't get enough usage to confirm or deny what I'm looking for.

**Comment by The-Compiler** [comment]
You can use `git bisect skip` for those.

**Comment by throwaway217** [comment]
What should I do if I keep encountering this no matter how many I skip ?

**Comment by The-Compiler** [comment]
That sounds odd. How exactly does it crash? If you do "git checkout master" (during the bisect) again, does it work?

**Comment by throwaway217** [comment]
Yes it works after I do git checkout master.

```
13:46:57 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/home/pun/qutebrowser/qutebrowser/app.py", line 863, in eventFilter
    return handler(event)
  File "/home/pun/qutebrowser/qutebrowser/app.py", line 823, in _handle_key_event
    return man.eventFilter(event)
  File "/home/pun/qutebrowser/qutebrowser/keyinput/modeman.py", line 318, in eventFilter
    return self._eventFilter_keypress(event)
  File "/home/pun/qutebrowser/qutebrowser/keyinput/modeman.py", line 170, in _eventFilter_keypress
    handled = parser.handle(event)
  File "/home/pun/qutebrowser/qutebrowser/keyinput/basekeyparser.py", line 309, in handle
    match = self._handle_single_key(e)
  File "/home/pun/qutebrowser/qutebrowser/keyinput/modeparsers.py", line 76, in _handle_single_key
    match = super()._handle_single_key(e)
  File "/home/pun/qutebrowser/qutebrowser/keyinput/basekeyparser.py", line 197, in _handle_single_key
    self.execute(binding, self.Type.chain, count)
  File "/home/pun/qutebrowser/qutebrowser/keyinput/keyparser.py", line 44, in execute
    self._commandrunner.run(cmdstr, count)
  File "/home/pun/qutebrowser/qutebrowser/commands/runners.py", line 294, in run
    result.cmd.run(self._win_id, args)
  File "/home/pun/qutebrowser/qutebrowser/commands/command.py", line 516, in run
    posargs, kwargs = self._get_call_args(win_id)
  File "/home/pun/qutebrowser/qutebrowser/commands/command.py", line 471, in _get_call_args
    value = self._get_param_value(param)
  File "/home/pun/qutebrowser/qutebrowser/commands/command.py", line 417, in _get_param_value
    elif issubclass(typ, typing.Union):
  File "/usr/lib/python3.6/typing.py", line 770, in __subclasscheck__
    raise TypeError("Unions cannot be used with issubclass().")
TypeError: Unions cannot be used with issubclass().
13:53:44 WARNING: The X11 connection broke (error 1). Did the X11 server die?
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pun/qutebrowser/qutebrowser/__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/pun/qutebrowser/qutebrowser/qutebrowser.py", line 163, in main
    return app.run(args)
  File "/home/pun/qutebrowser/qutebrowser/app.py", line 108, in run
    ret = qt_mainloop()
  File "/home/pun/qutebrowser/qutebrowser/app.py", line 118, in qt_mainloop
    return qApp.exec_()
  File "/home/pun/qutebrowser/qutebrowser/misc/crashsignal.py", line 255, in exception_hook
    ret = self._crash_dialog.exec_()
  File "/home/pun/qutebrowser/qutebrowser/utils/log.py", line 402, in qt_message_handler
    stack = ''.join(traceback.format_stack())

```

**Comment by lahwaacz** [comment]
Could you repeat that with `python3.5` to rule out problems with 3.6?

**Comment by throwaway217** [comment]
Done. Problematic behavior is gone and I no longer need to skip.

**Comment by The-Compiler** [comment]
FWIW that was fixed in b6195d4e77e1309b4b4ecf77508a9ad65b007fcc - I thought that was in v0.8.4, but apparently it's only in v0.9.0. I guess that was released just in time then 😆

**Comment by throwaway217** [comment]
I have 0 confidence in this. Without my restrictive config file I have no idea what I'm looking at is actual higher memory usage or one of the sites I'm visiting is web 5.0 retarded abomination like realmofmetal.org for example but if I try to load without --temp-basedir I always get conflicting configs and I need to change settings each time. Can I throw config parameters at qutebrowser as flags similar to --temp-basedir ?

**Comment by lahwaacz** [comment]
You can pass any command to qutebrowser on the command line (see `qutebrowser -h`). Or you can use `--relaxed-config` to silently remove unknown config options (you may want to backup first).

**Comment by throwaway217** [comment]
No offense but I give up for the moment. I've already allocated too much time to this today and gotten nowhere.I should I started with a 0.8.4 config 
![2017-01-06-154826_1366x768_scrot](https://cloud.githubusercontent.com/assets/24833941/21721280/ea8bb0b8-d427-11e6-82b6-88ef38cc7fcf.png)

**Comment by throwaway217** [comment]
I thought a little about this yesterday and I was thinking of running git bisect again today but there's something I don't understand.
If I downgrade to 0.8.4 right now, I still have the same high memory issue.What good would bisecting do ?

**Comment by The-Compiler** [comment]
Huh, but that's what this issue is about ("Higher memory usage since 0.9 update"), no? I'm confused...

**Comment by throwaway217** [comment]
Yes, that was the event that triggered it. It's all in the childish wall of text. I do not blame you for not reading it. https://github.com/The-Compiler/qutebrowser/issues/2201#issuecomment-270031431

**Comment by The-Compiler** [comment]
So let me recap - you're saying:

- You got around 500 MB initially
- With some unknown update, you got around 900 MB with v0.8.4
- With v0.9.0, you get about the same?

Maybe Python 3.6 causes this?

**Comment by throwaway217** [comment]
- I got around 500MB initially
- was using outdated repos, updated repo list from the archlinux mirror status, with the update came 0.9 and I noticed this behaviour 
- went back to 0.8.4 got around 900 MB
- with 0.9.0 I get around 1.1 GiB + 90.6 MiB = 1.2 GiB (right now actually )
- now no matter what I do I can't get to the initial state

I've tested both 0.8.4 on python 3.6 and 3.5, python 3.6 was pushed just recently to the non-testing repos  on arch.I think I tried making qutebrowser 0.8.4 and 0.9 with older versions of qt5-base and qt5-webkit but did not succeed. I also tried wayland, same thing.

**Comment by throwaway217** [comment]
And I see why you might think it's the same bug as the other but even though the end state is the same the initial factors seem different.I didn't restart and that instance that I got the ps_mem info from in my previous post and now it's:   1.8 GiB +  91.5 MiB =   1.9 GiB and the only thing I did was visit some imageboards a few times.

**Comment by lahwaacz** [comment]
I'd say it's pointless to try to solve problems with webkit when webengine is already coming. It would have been interesting to compare the memory usage of the webengine backend between the "initial" and "current" states, but since you can't get to the initial state, that is probably not applicable.

If you are as anxious about this as it seems from the discussion above, you might try to downgrade the whole system to the initial state using either your backups or the [Arch Linux Archive](https://wiki.archlinux.org/index.php/Arch_Linux_Archive). Btw. the packages that were updated are recorded in `/var/log/pacman.log`, along with the exact version numbers.

**Comment by The-Compiler** [comment]
I agree with @lahwaacz - what I'm still trying to find out is whether this is something caused by (or a regression in) qutebrowser's Python code, either by the qutebrowser or by the python upgrade.

@throwaway217, can you compare the solution with `--backend webengine`, i.e. have you ever measured RAM usage with that before it increased?

**Comment by throwaway217** [comment]
I stood away from webengine because I saw the a webengine-proxy branch. Is it safe to use with a proxy ?

**Comment by The-Compiler** [comment]
No, it doesn't have proxy support, and probably won't before Qt 5.8 because of a weird Qt/libproxy bug

**Comment by throwaway217** [comment]
After some time, I've finally caught the culprit/s, setting one or both of the following options to 0 and respectively 0,0,0 triggers this.

maximum-pages-in-cache
object-cache-capacities

Setting cache-size also increases RAM usage but nothing extraordinary.I am not able to test offline-* options. In order to evade this bug I just leave these 3 options as default.

**Comment by The-Compiler** [comment]
Closing this again then, as all qutebrowser does for those options is passing them to Qt.
